#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.116:3306/gdjrfwpt?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    hikari:
#      pool-name: principalHikariCP
#      maximum-pool-size: 5

spring:
  cloud:
    gateway:
      routes:
        - id: jiuwanziroute
          uri: http://192.168.1.138:8081
          predicates:
            - Path=/jiuwanzi/**