spring:
  datasource:
    url: jdbc:mysql://192.168.1.116:3306/zhtbbhw_menhu?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: principalHikariCP
      maximum-pool-size: 5
  jpa:
    show-sql: true